name: Code CI

on:
  push:
  pull_request:
env:
  # Target python version. Make sure Dockerfile FROM's match this.
  PYTHON: "3.10"
  TAGGED: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
  NOT_TAGGED1: ${{ ! (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) }}
  NOT_TAGGED2: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/tags') }}
  TRUE_BOOL: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # image names must be all lower case
      - run: |
          echo IMAGE_REPOSITORY=$(tr '[:upper:]' '[:lower:]' <<< "${{ github.repository }}") >> $GITHUB_ENV

      - name: environ
        run: |
          echo PYTHON ${{ env.PYTHON }} # works - 3.10
          echo IMAGE_REPOSITORY ${{ env.IMAGE_REPOSITORY }} # works

      - name: Job 1 TAGGED
        run: |
          echo TAGGED ${{ env.TAGGED }} # works - false
          echo TAGGED ${{ github.env.TAGGED }} # fails (blank - don't use github sub-context!)
          echo NOT TAGGED IN-LNE ${{ ! env.TAGGED }}
          echo NOT TAGGED IN-LNE ${{ !( env.TAGGED ) }}
          echo NOT TAGGED1 ${{ env.NOT_TAGGED1 }}
          echo NOT TAGGED2 ${{ env.NOT_TAGGED2 }}
          echo NOT TAGGED full ${{ ! (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) }}

      - name: Job 1 TRUE_BOOL
        run: |
          echo TRUE_BOOL ${{ env.TRUE_BOOL }} # works - true
          echo NOT TRUE_BOOL ${{ ! env.TRUE_BOOL }} # works - false

      - name: check not TAGGED env
        if: ${{ ! env.TAGGED }}
        run: echo HELLO # fails - does not run

      - name: check True bool env
        if: env.TRUE_BOOL
        run: echo HELLO # works - runs

      - name: check True bool env {}
        if: ${{ env.TRUE_BOOL }}
        run: echo HELLO # works runs

      - name: check False bool env
        if: ${{ ! env.TRUE_BOOL }}
        run: echo HELLO # works - does not run

      - name: check Blank
        if: ${{ env.NOTHING }}
        run: echo HELLO # works - does not run

      - name: check Blank
        if: ${{ ! env.NOTHING }}
        run: echo HELLO # does run - WAIT WHAT ????

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  test2:
    needs: test
    if: ${{ env.TRUE_BOOL == true}}
    runs-on: ubuntu-latest

    steps:
      - name: job 2 environ
        run: |
          echo PYTHON ${{ env.PYTHON }} # works
          echo TAGGED ${{ env.TAGGED }} # works
          echo IMAGE_REPOSITORY ${{ env.IMAGE_REPOSITORY }} # fails $GITHUB_ENV is local to job

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
